### PR TITLE
Fix filenames

### PR DESCRIPTION
**Pull request by CharlieADavies**
Hi there. This seems like a cool project, but clearly you're new to c plus plus, so you don't quite know that your file names should end with cpp - so I've fixed that for you!

good luck on your learning journey

### CODE REVIEW

**Comment by gitautas** [comment]
You need to update the `build.meson` file with the new filenames

**Review by gitautas — CHANGES_REQUESTED** [review]
Please update the build.meson with updated filenames

**Comment by gitautas** [comment]
`meson.build:35:0: ERROR: File jlog.hh does not exist.`

**Comment by mustafaquraish** [comment]
Real C++ programmers use `.h`, not `.hpp`

**Comment by gitautas** [comment]
@mustafaquraish emacs defaults to `c-mode` on .h files

**Comment by mustafaquraish** [comment]
> @mustafaquraish emacs defaults to `c-mode` on .h files

Use a good editor

**Comment by gitautas** [comment]
> Reference i

I sill sooner become a mechanic before I do that

**Pull request merged**
